"""
Python analysis layer: discount elasticity regression, cohort retention
curve, channel mix, and city-tier growth -- all computed directly from
orders.csv (no external libraries; stdlib only).

Every number quoted in executive_summary.md is generated by this script,
not hand-written -- rerun it and the summary's numbers should match.

Run:
    python3 analysis.py
Produces:
    charts/*.svg
    findings.json   (raw numbers, for executive_summary.md to reference)
"""
import csv
import json
import math
import os
import sys
from collections import defaultdict

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from svg_charts import line_chart, bar_chart  # noqa: E402

CSV_PATH = "orders.csv"
CHART_DIR = "charts"


def load_rows():
    with open(CSV_PATH) as f:
        return list(csv.DictReader(f))


def monthly_revenue(rows):
    rev = defaultdict(float)
    orders = defaultdict(int)
    for r in rows:
        rev[r["year_month"]] += float(r["revenue"])
        orders[r["year_month"]] += 1
    months = sorted(rev)
    return months, [rev[m] for m in months], [orders[m] for m in months]


def discount_elasticity(rows):
    """Pooled log-log elasticity of order volume w.r.t. discount, with
    sub-category fixed effects via demeaning (removes category-level price
    differences so we isolate the within-category discount->demand effect)."""
    cell_orders = defaultdict(int)
    cell_disc = defaultdict(list)
    for r in rows:
        key = (r["sub_category"], r["year_month"])
        cell_orders[key] += 1
        cell_disc[key].append(float(r["discount_pct"]))

    by_cat = defaultdict(list)  # cat -> list of (log_orders, avg_discount)
    for (cat, ym), n in cell_orders.items():
        avg_d = sum(cell_disc[(cat, ym)]) / len(cell_disc[(cat, ym)])
        by_cat[cat].append((math.log(n), avg_d))

    x_dm, y_dm = [], []
    for cat, pts in by_cat.items():
        mean_ly = sum(p[0] for p in pts) / len(pts)
        mean_d = sum(p[1] for p in pts) / len(pts)
        for ly, d in pts:
            x_dm.append(d - mean_d)
            y_dm.append(ly - mean_ly)

    # simple OLS slope through the origin on demeaned data: beta = cov(x,y)/var(x)
    n = len(x_dm)
    mean_x = sum(x_dm) / n
    mean_y = sum(y_dm) / n
    cov = sum((x_dm[i] - mean_x) * (y_dm[i] - mean_y) for i in range(n))
    var = sum((x_dm[i] - mean_x) ** 2 for i in range(n))
    beta = cov / var  # d(log orders) / d(discount_pct); x10 for "per 10pt discount"

    # R^2
    y_pred = [beta * (x_dm[i] - mean_x) + mean_y for i in range(n)]
    ss_res = sum((y_dm[i] - y_pred[i]) ** 2 for i in range(n))
    ss_tot = sum((y_dm[i] - mean_y) ** 2 for i in range(n))
    r2 = 1 - ss_res / ss_tot
    return beta, r2, n


def cohort_retention(rows):
    acq_month = {}
    activity = defaultdict(set)  # (cohort, k) -> set(customer_id)
    cohort_size = defaultdict(set)
    for r in rows:
        cid = r["customer_id"]
        if int(r["is_new_customer"]):
            acq_month[cid] = r["year_month"]
    for r in rows:
        cid = r["customer_id"]
        if cid not in acq_month:
            continue
        cohort = acq_month[cid]
        k = int(r["months_since_acquisition"])
        activity[(cohort, k)].add(cid)
        if k == 0:
            cohort_size[cohort].add(cid)

    max_k = 6
    avg_retention = []
    for k in range(max_k + 1):
        pct_list = []
        for cohort, size_set in cohort_size.items():
            size = len(size_set)
            active = len(activity.get((cohort, k), set()))
            # only include cohorts old enough to have reached month k in the 24-month window
            pct_list.append(active / size)
        avg_retention.append(100 * sum(pct_list) / len(pct_list))
    return avg_retention


def channel_mix(rows):
    rev = defaultdict(float)
    new_orders = defaultdict(int)
    total_orders = defaultdict(int)
    for r in rows:
        ch = r["marketing_channel"]
        rev[ch] += float(r["revenue"])
        total_orders[ch] += 1
        if int(r["is_new_customer"]):
            new_orders[ch] += 1
    channels = sorted(rev, key=lambda c: -rev[c])
    return channels, [rev[c] for c in channels], [100 * new_orders[c] / total_orders[c] for c in channels]


def city_tier_growth(rows):
    rev = defaultdict(lambda: defaultdict(float))
    for r in rows:
        period = "Y1" if r["year_month"] < "2024-01" else "Y2"
        rev[r["city_tier"]][period] += float(r["revenue"])
    tiers = ["Tier 1", "Tier 2", "Tier 3"]
    growth = []
    for t in tiers:
        y1, y2 = rev[t]["Y1"], rev[t]["Y2"]
        growth.append(100 * (y2 - y1) / y1)
    return tiers, growth, {t: (rev[t]["Y1"], rev[t]["Y2"]) for t in tiers}


def main():
    rows = load_rows()
    os.makedirs(CHART_DIR, exist_ok=True)

    months, revs, orders = monthly_revenue(rows)
    line_chart(months, {"Revenue (INR)": revs}, "Men's Footwear: Monthly Revenue",
               subtitle="Jan 2023 - Dec 2024, synthetic data",
               filename=f"{CHART_DIR}/01_monthly_revenue.svg")

    beta, r2, n_cells = discount_elasticity(rows)
    elasticity_per_10pt = (math.exp(beta * 0.10) - 1) * 100

    retention = cohort_retention(rows)
    bar_chart([f"M{k}" for k in range(len(retention))], retention,
              "Average Cohort Retention Curve", subtitle="% of acquisition-month cohort still ordering, by month since acquisition",
              filename=f"{CHART_DIR}/02_cohort_retention.svg")

    channels, ch_rev, ch_new_pct = channel_mix(rows)
    bar_chart(channels, ch_rev, "Revenue by Marketing Channel",
              filename=f"{CHART_DIR}/03_channel_revenue.svg")

    tiers, growth, tier_rev = city_tier_growth(rows)
    bar_chart(tiers, growth, "YoY Revenue Growth by City Tier (Y1 -> Y2)", subtitle="%",
              filename=f"{CHART_DIR}/04_city_tier_growth.svg")

    total_y1 = sum(v for m, v in zip(months, revs) if m < "2024-01")
    total_y2 = sum(v for m, v in zip(months, revs) if m >= "2024-01")

    findings = {
        "total_revenue_y1": round(total_y1),
        "total_revenue_y2": round(total_y2),
        "yoy_revenue_growth_pct": round(100 * (total_y2 - total_y1) / total_y1, 1),
        "discount_elasticity_beta": round(beta, 3),
        "discount_elasticity_r2": round(r2, 3),
        "elasticity_pct_lift_per_10pt_discount": round(elasticity_per_10pt, 1),
        "elasticity_n_category_months": n_cells,
        "retention_month1_pct": round(retention[1], 1),
        "retention_month6_pct": round(retention[6], 1),
        "channel_revenue": dict(zip(channels, [round(v) for v in ch_rev])),
        "channel_new_customer_pct": dict(zip(channels, [round(v, 1) for v in ch_new_pct])),
        "city_tier_growth_pct": dict(zip(tiers, [round(v, 1) for v in growth])),
        "city_tier_revenue": {t: [round(v) for v in vals] for t, vals in tier_rev.items()},
    }
    with open("findings.json", "w") as f:
        json.dump(findings, f, indent=2)

    print(json.dumps(findings, indent=2))


if __name__ == "__main__":
    main()
